-- 各種テーブル削除
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

-- タスクテーブル
CREATE TABLE tasks
(
   task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id INTEGER,
   category_id INTEGER,
   title VARCHAR(255),
   closing_date DATE,
   progress INTEGER,
   memo TEXT,
   time INTEGER,
   date DATE
--   FOREIGN KEY (user_id) REFERENCES users(user_id),
--   FOREIGN KEY (category_id) REFERENCES categories(category_id)
);
-- カテゴリテーブル
CREATE TABLE categories
(
   category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   category_name VARCHAR(20)
);
-- ユーザーテーブル
CREATE TABLE users
(
   user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(20),
   password TEXT
);
